name: Build LaTeX document (using Docker)

on:
  push:
    branches: [ "main" ]
  pull_request:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Compile LaTeX - main
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
        
      - name: Compile LaTeX - Link MRE
        uses: xu-cheng/latex-action@v3
        with:
          root_file: MRE_AnchorLink.tex
        
      - name: Compile LaTeX - Skill MRE
        uses: xu-cheng/latex-action@v3
        with:
          root_file: MRE_SkillTable.tex
        
      - name: Compile LaTeX - Perk MRE
        uses: xu-cheng/latex-action@v3
        with:
          root_file: MRE_Perk.tex

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: pdfs
          path: '*.pdf'
      
      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: latex-logs
          path: '*.log'

      - name: Check for undefined references
        run: |
          echo "Searching for undefined LaTeX references in main.log..."
          if [ -f main.log ]; then
            # Join wrapped lines and extract all 'Reference ... undefined' warnings
            awk '
              { if (NF == 0) next }
              /LaTeX Warning: Reference/ { printf "%s ", $0; next }
              /undefined on input line/ { print $0 }
            ' main.log | sed 's/  */ /g'
          else
            echo "No main.log file found!"
          fi
