name: Build LaTeX documents (using Docker)

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Compile multiple LaTeX files in a single Docker session
      - name: Compile LaTeX documents
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          args: >
            latexmk -pdf main.tex &&
            latexmk -pdf MakeAnchorMakeLink_MRE.tex

      # Upload both PDFs as artifacts
      - name: Upload PDF artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pdf-artifacts
          path: |
            main.pdf
            MakeAnchorMakeLink_MRE.pdf
