name: Build LaTeX document (using Docker)

on:
  push:
    branches: [ "main" ]
  pull_request:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
        
      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: MakeAnchorMakeLink_MRE.tex
        
      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: SkillTable_MRE.tex

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: pdfs
          path: '*.pdf'
